### ISSUE TITLE
Custom containers are not marked as deleted

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#400] opened 2019-11-25 15:26 UTC
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
If you create a custom container and publish it, it will remain in the bucket even after it's been deleted, and has no deletedAt property.

![Screen Shot 2019-11-25 at 16 23 23](https://user-images.githubusercontent.com/34127147/69553351-598fc600-0fa0-11ea-803f-a27138a8c62c.png)

**Comment by abasic** [comment] 2020-10-25 16:54
@kjuej @underscope As far as I can tell, regular content containers also do not get deleted nor do they get a deletedAt flag. What is the desired/expected behavior here?

**Comment by abasic** [comment] 2020-10-27 15:54
@kjuej @underscope 

Looking at what to do here, I see three options:

- remove the file when the container is deleted,
- mark on S3 that the container is deleted,
- leave as is.

The first and third options are obvious. The second one, I think, is trickier because I do not see value in marking inside of the file since the container reference is deleted from the `contentContainers` prop inside the parent's `index.json.` I believe, if we went with the second option, it should no longer be deleted from the `contentContainers` prop but marked as deleted there instead of the file itself. But this approach has compatibility issues since there would be existing published content that has deleted content containers from that prop. And they could find themselves in a situation where they have multiple deleted content containers; some fully removed and some marked as such. I do not think we gain much from this approach other then headache. If we decided to go this way I believe we should republish all existing activities with the `contentContainers` prop updated. Also, with this approach, all of the consumers of the published content need to be updated to handle the deletion flag.

So, to me, the options are to leave as is or to remove them. The cleaner approach is to remove them since nobody should be using them after they are deleted but I do not have an issue with leaving as is. What do you think?

**Closed** 2021-02-14 13:49 UTC
Labels: :rotating_light: bug, 🔨contribution is welcomed
